language: python
python:
- '3.4'
- '3.5'
- nightly
install:
- pip3 install pylint scapy-python3
script: python setup.py install && pylint *.py -E
deploy:
  provider: pypi
  user: fabiocody
  password:
    secure: k/1zcVl/AIJ8dk30rEOapLVeJi9q3lVUZ4vgiiZdSWBt9E0+mMfXlYeVOU8pDfW2mXDZs+UFebkWJZVW5mPaGQMHQhIg+HKwQUdkdI9JKVmHpD9roHDcFwL7th+NwG53xHyPdj7LUtOPteyFaOShO8eu0bcIyIPF8wIa/6REmj4CzEc6Q18NLbFap70kNeOGTHmYPGyrJDjV4bpGpiKzHxV4mb2ORLyvX1bcFSCHH0xeBGvz9HCUdLWqU3YorPotlBA5zWdL6172gzpFTLiiVLYX1/U1FUuLk86Be3DCNdYelNwNkrYcfU8LByqkq2i96tqy9fpa6pn/JTNHrW96Vj+t02dADOT2360/jBHjr4W1VaI7csygYBTyYYN9XbSNtzc3OhSxHks526siZ0LZxYI4OdNWH8FRbXY4qLx8QTi/EpEVRCFudZWOV6dLS3AfT9iZsO3Apz6I7dk8nja3TT+nfufQRLn3uoJ9oeXMz0CLoL7qhkPSQN91WtIAMulHfudJ8xQ+BgWI3k+KWpsQOT/SaWqRK+z4j8DPIT0KDZM6WMfyBK/zsxMr9RGHM710Y+sVJXLksoWfKouOgWinylguhBAdBrDMRwnzC8PNq6wfDa6ax+Yr0nihSIw54EAA15i27Ub8Pt87cYANkg9sMSP4brRa9JX/8RTNt9Kjxkc=
  on:
    tags: true
    branch: master
